// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khuzyceafmvlicjhoyfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtodXp5Y2VhZm12bGljamhveWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTkyNTAsImV4cCI6MjA3MTA5NTI1MH0.Cw3DwcLxI_q26tJ5nCpeqi3dkfrg5ibD-4Wqo__lNkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});